services:
    php:
        build:
            context: ./.docker/php
            container_name: php_fpm
            dockerfile: Dockerfile
            image: php:php:8.4.2-fpm
            volumes:
                - .:/var/www/html
            networks:
                - php_network
    nginx:
        build:
            context: ./.docker/nginx
            container_name: nginx_server
            dockerfile: Dockerfile
            image: nginx:1.27.3-alpine-slim
            volumes:
                - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
                - ./data:/var/www/html
            ports:
                - "8000:80"
            networks:
                - php_network
    mysql:
        build:
            context: ./.docker/mysql
            container_name: mysql_server
            dockerfile: Dockerfile
            image: mysql:8.4.0
            environment:
                MYSQL_ROOT_PASSWORD: root
            volumes:
                - .:/var/www/html
            ports:
                - "3360:3306"
            networks:
                - php_network
networks:
    php_network:
        driver: bridge
        name: php_network

